- name: nginx
  ansible.builtin.package:
    name: nginx
    state: present
- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: Remove file 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Create a directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: Download conf
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
- name: unarchive file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: coping file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  notify: 
  - restart nginx